name: Deploy prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy_server:
    permissions:
      id-token: write
    uses: ./.github/workflows/build-graphql.yml
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      aws_region: $AWS_REGION
      environment: prod
